# ==========================================
# Datasource - PostgreSQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/shopping_cart_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# App
# ==========================================
spring.application.name=shopping-cart
server.port=8080

# ==========================================
# Swagger / SpringDoc OpenAPI
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.corhuila.shoppingcart.controllers

# ==========================================
# CORS
# ==========================================
spring.mvc.cors.allowed-origins=http://localhost:4200

